# Generated by Django 3.0.4 on 2021-04-17 16:08

import appArticle.models
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文章种类')),
                ('url', models.CharField(blank=True, editable=False, help_text='管理系统自行维护', max_length=255, null=True, verbose_name='URL')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='位置')),
                ('createDatetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '1.文章种类',
                'verbose_name_plural': '1.文章种类',
            },
        ),
        migrations.CreateModel(
            name='TagKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, help_text='关键字使用英文逗号隔开","', null=True, verbose_name='分类标签')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='appArticle.Category', verbose_name='文章种类')),
            ],
            options={
                'verbose_name': '2.关键字',
                'verbose_name_plural': '2.关键字',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('articleType', models.PositiveSmallIntegerField(choices=[(1, '站内文章'), (2, '站外文章'), (3, 'PDF')], default=1, verbose_name='文章种类')),
                ('outlink', models.CharField(blank=True, max_length=255, null=True, verbose_name='外部链接地址')),
                ('url', models.CharField(blank=True, help_text='站内文章或PDF的地址，管理系统自行维护', max_length=255, null=True, verbose_name='文章地址')),
                ('pdflink', models.FileField(blank=True, null=True, upload_to=appArticle.models.upload_pdflink, verbose_name='PDF地址')),
                ('ppicture', models.FileField(blank=True, null=True, upload_to=appArticle.models.upload_ppicture, verbose_name='配图')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源')),
                ('createDatetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('clickNum', models.IntegerField(default=0, verbose_name='点击数量')),
                ('collectNum', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('video', models.FileField(blank=True, null=True, upload_to=appArticle.models.upload_video, verbose_name='视频')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='文章位置')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='appArticle.Category', verbose_name='文章种类')),
            ],
            options={
                'verbose_name': '3.文章详细',
                'verbose_name_plural': '3.文章详细',
            },
        ),
    ]
